-- Set up Snowflake environment
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

-- Create a database and schema for this project
CREATE DATABASE IF NOT EXISTS SECURITY_ANALYTICS;
USE DATABASE SECURITY_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS CIC_IDS2018;
USE SCHEMA CIC_IDS2018;
